server:
  port: 8080

spring:
  application:
    name: "Authentication"

  devtools:
    add-properties: false

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: postgres

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  logging:
    level:
      org.springframework.r2dbc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
